const assert = require('node:assert/strict');
const fs = require('node:fs');
const {webcrypto} = require('node:crypto');
const {EventTarget, Event} = global;
(async () => {
  global.crypto ??= webcrypto;
  const source = fs.readFileSync('libraries/app-sdk/src/our_ark_app_sdk/static/activity.js', 'utf8');
  const {ActivityReporter} = await import('data:text/javascript;base64,' + Buffer.from(source).toString('base64'));
  const doc = new EventTarget(), win = new EventTarget();
  let focused = true, heartbeat, interval, page = {product_id: 'day-one'}, failContext = false;
  Object.assign(doc, {visibilityState: 'visible', hasFocus: () => focused});
  Object.assign(win, {setInterval: (fn, ms) => { heartbeat = fn; interval = ms; return 1; }, clearInterval: () => {heartbeat = null;}});
  const values = new Map();
  const storage = {getItem: k => values.get(k), setItem: (k,v) => values.set(k,v)};
  const sent = [];
  const request = async (path, body) => {
    assert.equal(path, '/ui/activity'); sent.push(body);
    if (failContext && body.type === 'context.updated') throw Error('offline');
    return {accepted: true};
  };
  const reporter = new ActivityReporter({request, sessionId:'tab1', context:() => page, doc, win, storage});
  const flush = () => new Promise(resolve => setImmediate(resolve));
  reporter.start(); await flush();
  assert.equal(interval, 15000);
  assert.equal(sent[0].state, 'active');
  assert.deepEqual(sent[1].context, {product_id:'day-one'});
  const contexts = () => sent.filter(e => e.type === 'context.updated');
  heartbeat(); await flush();
  assert.equal(contexts().length, 1, 'unchanged context is coalesced');
  page = {product_id:'arc-02'}; failContext = true;
  await reporter.contextChanged(); failContext = false;
  heartbeat(); await flush();
  assert.equal(contexts().at(-1).context.product_id, 'arc-02', 'failed context retries');
  focused = false; win.dispatchEvent(new Event('blur')); await flush();
  assert.equal(sent.at(-1).state, 'inactive');
  let count = sent.length; heartbeat(); await flush();
  assert.equal(sent.length, count, 'background tabs do not heartbeat');
  focused = true; doc.visibilityState = 'hidden';
  doc.dispatchEvent(new Event('visibilitychange')); await flush();
  assert.equal(sent.at(-1).state, 'inactive', 'hidden pages cannot claim focus');
  doc.visibilityState = 'visible'; win.dispatchEvent(new Event('focus')); await flush();
  assert.equal(sent.at(-1).state, 'active');
  win.dispatchEvent(new Event('pagehide')); await flush();
  assert.equal(sent.at(-1).state, 'inactive');
  reporter.stop(); await flush();
  assert.equal(heartbeat, null);
  count = sent.length; win.dispatchEvent(new Event('focus')); await flush();
  assert.equal(sent.length, count, 'listeners removed on disconnect');
  const next = new ActivityReporter({request, sessionId:'tab1', context:() => page, doc, win, storage});
  next.start(); await flush(); next.stop(); await flush();
  assert.ok(sent.every((e,i) => !i || e.sequence > sent[i-1].sequence), 'sequence survives reload');
  console.log('Activity UI focus, visibility, heartbeat, context retry, reload and cleanup passed.');
})().catch(e => {console.error(e); process.exitCode=1;});
